### ISSUE TITLE
Error with Single Step Intro

### ISSUE THREAD

**Issue by flavioamc** [HiDeoo/intro.js-react#22] opened 2018-08-16 15:07 UTC
Is single step intro supported by intro.js-react?

My code:

```
renderSliderTooltip() {
    const { showFirstTooltip } = this.state
    let component = null

    const steps = [
      {
        element: '.start-step1',
        intro: 'Toque aqui para <strong>completar esse pack TOP!</strong>',
        position: 'top',
        tooltipClass: 'promo-pack-btn-tooltip promo-pack-tooltip',
        highlightClass: 'promo-pack-highlight'
      },
      {
        element: '.end-step1',
        intro: 'end',
      }
    ];

    const opt = {
      showButtons: false,
      showStepNumbers: false,
      showBullets: false,
    };

    if (showFirstTooltip) {
      component = (
        <Steps
          enabled={true}
          initialStep={0}
          steps={steps}
          onExit={e => this._exitSliderTooltip()}
          options={opt}
        />
      )
    }

    return component
  }
```
Without the 'end-step1' class put in the same element, the component breaks

Console error:
![error](https://user-images.githubusercontent.com/3398335/44216861-64786b80-a14c-11e8-802d-a4e7620bb4b9.png)

Am I missing something?

Thanks

**Comment by HiDeoo** [comment] 2018-08-16 15:32
Looks like this might be a duplicate of #20.

In [this comment](https://github.com/HiDeoo/intro.js-react/issues/20#issuecomment-403604901), I describe what might be a part of the issue if there is still no PR for it.

**Closed by HiDeoo** 2018-08-16 15:32 UTC
